// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionType int32

const (
	ExtensionType_EXTENSION_TYPE_UNSPECIFIED ExtensionType = 0
	ExtensionType_EXTENSION_TYPE_DATASOURCE  ExtensionType = 1
)

// Enum value maps for ExtensionType.
var (
	ExtensionType_name = map[int32]string{
		0: "EXTENSION_TYPE_UNSPECIFIED",
		1: "EXTENSION_TYPE_DATASOURCE",
	}
	ExtensionType_value = map[string]int32{
		"EXTENSION_TYPE_UNSPECIFIED": 0,
		"EXTENSION_TYPE_DATASOURCE":  1,
	}
)

func (x ExtensionType) Enum() *ExtensionType {
	p := new(ExtensionType)
	*p = x
	return p
}

func (x ExtensionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (ExtensionType) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[0]
}

func (x ExtensionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionType.Descriptor instead.
func (ExtensionType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_READY       HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_NOT_READY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_READY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_NOT_READY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_READY":       1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_NOT_READY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type PluginError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	SafeMessage   string                 `protobuf:"bytes,2,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginError) Reset() {
	*x = PluginError{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginError) ProtoMessage() {}

func (x *PluginError) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginError.ProtoReflect.Descriptor instead.
func (*PluginError) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PluginError) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

type HandshakeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PluginId             string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion        string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ExtensionId          string                 `protobuf:"bytes,3,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	ExtensionType        ExtensionType          `protobuf:"varint,4,opt,name=extension_type,json=extensionType,proto3,enum=weknora.plugin.v1.ExtensionType" json:"extension_type,omitempty"`
	ProtocolVersion      string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ContractVersion      string                 `protobuf:"bytes,6,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	StartupNonce         []byte                 `protobuf:"bytes,7,opt,name=startup_nonce,json=startupNonce,proto3" json:"startup_nonce,omitempty"`
	RequiredCapabilities []string               `protobuf:"bytes,8,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeRequest) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HandshakeRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *HandshakeRequest) GetExtensionType() ExtensionType {
	if x != nil {
		return x.ExtensionType
	}
	return ExtensionType_EXTENSION_TYPE_UNSPECIFIED
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *HandshakeRequest) GetStartupNonce() []byte {
	if x != nil {
		return x.StartupNonce
	}
	return nil
}

func (x *HandshakeRequest) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

type HandshakeResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PluginId              string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion         string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ExtensionId           string                 `protobuf:"bytes,3,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	ExtensionType         ExtensionType          `protobuf:"varint,4,opt,name=extension_type,json=extensionType,proto3,enum=weknora.plugin.v1.ExtensionType" json:"extension_type,omitempty"`
	ProtocolVersion       string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ContractVersion       string                 `protobuf:"bytes,6,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	StartupNonce          []byte                 `protobuf:"bytes,7,opt,name=startup_nonce,json=startupNonce,proto3" json:"startup_nonce,omitempty"`
	SupportedCapabilities []string               `protobuf:"bytes,8,rep,name=supported_capabilities,json=supportedCapabilities,proto3" json:"supported_capabilities,omitempty"`
	Error                 *PluginError           `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HandshakeResponse) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *HandshakeResponse) GetExtensionType() ExtensionType {
	if x != nil {
		return x.ExtensionType
	}
	return ExtensionType_EXTENSION_TYPE_UNSPECIFIED
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *HandshakeResponse) GetStartupNonce() []byte {
	if x != nil {
		return x.StartupNonce
	}
	return nil
}

func (x *HandshakeResponse) GetSupportedCapabilities() []string {
	if x != nil {
		return x.SupportedCapabilities
	}
	return nil
}

func (x *HandshakeResponse) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateConfigRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *PluginError           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateConfigResponse) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=weknora.plugin.v1.HealthStatus" json:"status,omitempty"`
	Error         *PluginError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *HealthResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceMillis   int64                  `protobuf:"varint,1,opt,name=grace_millis,json=graceMillis,proto3" json:"grace_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownRequest) GetGraceMillis() int64 {
	if x != nil {
		return x.GraceMillis
	}
	return 0
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ListResourcesRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ListResourcesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Error         *PluginError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasChildren   bool                   `protobuf:"varint,8,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *Resource) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type ResolveAncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAncestorsRequest) Reset() {
	*x = ResolveAncestorsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAncestorsRequest) ProtoMessage() {}

func (x *ResolveAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAncestorsRequest.ProtoReflect.Descriptor instead.
func (*ResolveAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveAncestorsRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ResolveAncestorsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type ResolveAncestorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AncestorIds   []string               `protobuf:"bytes,1,rep,name=ancestor_ids,json=ancestorIds,proto3" json:"ancestor_ids,omitempty"`
	Error         *PluginError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAncestorsResponse) Reset() {
	*x = ResolveAncestorsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAncestorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAncestorsResponse) ProtoMessage() {}

func (x *ResolveAncestorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAncestorsResponse.ProtoReflect.Descriptor instead.
func (*ResolveAncestorsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveAncestorsResponse) GetAncestorIds() []string {
	if x != nil {
		return x.AncestorIds
	}
	return nil
}

func (x *ResolveAncestorsResponse) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type SyncRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson        []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	CursorJson        []byte                 `protobuf:"bytes,2,opt,name=cursor_json,json=cursorJson,proto3" json:"cursor_json,omitempty"`
	ForceFull         bool                   `protobuf:"varint,3,opt,name=force_full,json=forceFull,proto3" json:"force_full,omitempty"`
	MultimodalEnabled bool                   `protobuf:"varint,4,opt,name=multimodal_enabled,json=multimodalEnabled,proto3" json:"multimodal_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *SyncRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *SyncRequest) GetCursorJson() []byte {
	if x != nil {
		return x.CursorJson
	}
	return nil
}

func (x *SyncRequest) GetForceFull() bool {
	if x != nil {
		return x.ForceFull
	}
	return false
}

func (x *SyncRequest) GetMultimodalEnabled() bool {
	if x != nil {
		return x.MultimodalEnabled
	}
	return false
}

type SyncEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SyncEvent_Upsert
	//	*SyncEvent_Delete
	//	*SyncEvent_ItemError
	//	*SyncEvent_Checkpoint
	Event         isSyncEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *SyncEvent) GetEvent() isSyncEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SyncEvent) GetUpsert() *DocumentUpsert {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *SyncEvent) GetDelete() *DocumentDelete {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *SyncEvent) GetItemError() *ItemError {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_ItemError); ok {
			return x.ItemError
		}
	}
	return nil
}

func (x *SyncEvent) GetCheckpoint() *Checkpoint {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

type isSyncEvent_Event interface {
	isSyncEvent_Event()
}

type SyncEvent_Upsert struct {
	Upsert *DocumentUpsert `protobuf:"bytes,1,opt,name=upsert,proto3,oneof"`
}

type SyncEvent_Delete struct {
	Delete *DocumentDelete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type SyncEvent_ItemError struct {
	ItemError *ItemError `protobuf:"bytes,3,opt,name=item_error,json=itemError,proto3,oneof"`
}

type SyncEvent_Checkpoint struct {
	Checkpoint *Checkpoint `protobuf:"bytes,4,opt,name=checkpoint,proto3,oneof"`
}

func (*SyncEvent_Upsert) isSyncEvent_Event() {}

func (*SyncEvent_Delete) isSyncEvent_Event() {}

func (*SyncEvent_ItemError) isSyncEvent_Event() {}

func (*SyncEvent_Checkpoint) isSyncEvent_Event() {}

type DocumentUpsert struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExternalId       string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Revision         string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content          []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType      string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileName         string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Url              string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourceResourceId string                 `protobuf:"bytes,10,opt,name=source_resource_id,json=sourceResourceId,proto3" json:"source_resource_id,omitempty"`
	ReplacesSubtree  bool                   `protobuf:"varint,11,opt,name=replaces_subtree,json=replacesSubtree,proto3" json:"replaces_subtree,omitempty"`
	SubtreeKeep      []string               `protobuf:"bytes,12,rep,name=subtree_keep,json=subtreeKeep,proto3" json:"subtree_keep,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DocumentUpsert) Reset() {
	*x = DocumentUpsert{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpsert) ProtoMessage() {}

func (x *DocumentUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpsert.ProtoReflect.Descriptor instead.
func (*DocumentUpsert) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *DocumentUpsert) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DocumentUpsert) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *DocumentUpsert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentUpsert) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocumentUpsert) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DocumentUpsert) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentUpsert) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocumentUpsert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DocumentUpsert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentUpsert) GetSourceResourceId() string {
	if x != nil {
		return x.SourceResourceId
	}
	return ""
}

func (x *DocumentUpsert) GetReplacesSubtree() bool {
	if x != nil {
		return x.ReplacesSubtree
	}
	return false
}

func (x *DocumentUpsert) GetSubtreeKeep() []string {
	if x != nil {
		return x.SubtreeKeep
	}
	return nil
}

type DocumentDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDelete) Reset() {
	*x = DocumentDelete{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDelete) ProtoMessage() {}

func (x *DocumentDelete) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDelete.ProtoReflect.Descriptor instead.
func (*DocumentDelete) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *DocumentDelete) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DocumentDelete) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ItemError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	SafeMessage   string                 `protobuf:"bytes,3,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemError) Reset() {
	*x = ItemError{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemError) ProtoMessage() {}

func (x *ItemError) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemError.ProtoReflect.Descriptor instead.
func (*ItemError) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ItemError) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ItemError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ItemError) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CursorJson    []byte                 `protobuf:"bytes,1,opt,name=cursor_json,json=cursorJson,proto3" json:"cursor_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Checkpoint) GetCursorJson() []byte {
	if x != nil {
		return x.CursorJson
	}
	return nil
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\x11weknora.plugin.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\vPluginError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fsafe_message\x18\x02 \x01(\tR\vsafeMessage\"\xf2\x02\n" +
	"\x10HandshakeRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12!\n" +
	"\fextension_id\x18\x03 \x01(\tR\vextensionId\x12G\n" +
	"\x0eextension_type\x18\x04 \x01(\x0e2 .weknora.plugin.v1.ExtensionTypeR\rextensionType\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12)\n" +
	"\x10contract_version\x18\x06 \x01(\tR\x0fcontractVersion\x12#\n" +
	"\rstartup_nonce\x18\a \x01(\fR\fstartupNonce\x123\n" +
	"\x15required_capabilities\x18\b \x03(\tR\x14requiredCapabilities\"\xab\x03\n" +
	"\x11HandshakeResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12!\n" +
	"\fextension_id\x18\x03 \x01(\tR\vextensionId\x12G\n" +
	"\x0eextension_type\x18\x04 \x01(\x0e2 .weknora.plugin.v1.ExtensionTypeR\rextensionType\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12)\n" +
	"\x10contract_version\x18\x06 \x01(\tR\x0fcontractVersion\x12#\n" +
	"\rstartup_nonce\x18\a \x01(\fR\fstartupNonce\x125\n" +
	"\x16supported_capabilities\x18\b \x03(\tR\x15supportedCapabilities\x124\n" +
	"\x05error\x18\t \x01(\v2\x1e.weknora.plugin.v1.PluginErrorR\x05error\"8\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"N\n" +
	"\x16ValidateConfigResponse\x124\n" +
	"\x05error\x18\x01 \x01(\v2\x1e.weknora.plugin.v1.PluginErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xba\x01\n" +
	"\x0eHealthResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.weknora.plugin.v1.HealthStatusR\x06status\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.weknora.plugin.v1.PluginErrorR\x05error\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"4\n" +
	"\x0fShutdownRequest\x12!\n" +
	"\fgrace_millis\x18\x01 \x01(\x03R\vgraceMillis\"T\n" +
	"\x14ListResourcesRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"\x88\x01\n" +
	"\x15ListResourcesResponse\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.weknora.plugin.v1.ResourceR\tresources\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.weknora.plugin.v1.PluginErrorR\x05error\"\xa9\x02\n" +
	"\bResource\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12!\n" +
	"\fhas_children\x18\b \x01(\bR\vhasChildren\x12#\n" +
	"\rmetadata_json\x18\t \x01(\fR\fmetadataJson\"]\n" +
	"\x17ResolveAncestorsRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\"s\n" +
	"\x18ResolveAncestorsResponse\x12!\n" +
	"\fancestor_ids\x18\x01 \x03(\tR\vancestorIds\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.weknora.plugin.v1.PluginErrorR\x05error\"\x9d\x01\n" +
	"\vSyncRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1f\n" +
	"\vcursor_json\x18\x02 \x01(\fR\n" +
	"cursorJson\x12\x1d\n" +
	"\n" +
	"force_full\x18\x03 \x01(\bR\tforceFull\x12-\n" +
	"\x12multimodal_enabled\x18\x04 \x01(\bR\x11multimodalEnabled\"\x8e\x02\n" +
	"\tSyncEvent\x12;\n" +
	"\x06upsert\x18\x01 \x01(\v2!.weknora.plugin.v1.DocumentUpsertH\x00R\x06upsert\x12;\n" +
	"\x06delete\x18\x02 \x01(\v2!.weknora.plugin.v1.DocumentDeleteH\x00R\x06delete\x12=\n" +
	"\n" +
	"item_error\x18\x03 \x01(\v2\x1c.weknora.plugin.v1.ItemErrorH\x00R\titemError\x12?\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x1d.weknora.plugin.v1.CheckpointH\x00R\n" +
	"checkpointB\a\n" +
	"\x05event\"\x90\x04\n" +
	"\x0eDocumentUpsert\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12K\n" +
	"\bmetadata\x18\t \x03(\v2/.weknora.plugin.v1.DocumentUpsert.MetadataEntryR\bmetadata\x12,\n" +
	"\x12source_resource_id\x18\n" +
	" \x01(\tR\x10sourceResourceId\x12)\n" +
	"\x10replaces_subtree\x18\v \x01(\bR\x0freplacesSubtree\x12!\n" +
	"\fsubtree_keep\x18\f \x03(\tR\vsubtreeKeep\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x0eDocumentDelete\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"c\n" +
	"\tItemError\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fsafe_message\x18\x03 \x01(\tR\vsafeMessage\"-\n" +
	"\n" +
	"Checkpoint\x12\x1f\n" +
	"\vcursor_json\x18\x01 \x01(\fR\n" +
	"cursorJson*N\n" +
	"\rExtensionType\x12\x1e\n" +
	"\x1aEXTENSION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EXTENSION_TYPE_DATASOURCE\x10\x01*\x7f\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HEALTH_STATUS_READY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_NOT_READY\x10\x032\xe5\x02\n" +
	"\rPluginControl\x12V\n" +
	"\tHandshake\x12#.weknora.plugin.v1.HandshakeRequest\x1a$.weknora.plugin.v1.HandshakeResponse\x12e\n" +
	"\x0eValidateConfig\x12(.weknora.plugin.v1.ValidateConfigRequest\x1a).weknora.plugin.v1.ValidateConfigResponse\x12M\n" +
	"\x06Health\x12 .weknora.plugin.v1.HealthRequest\x1a!.weknora.plugin.v1.HealthResponse\x12F\n" +
	"\bShutdown\x12\".weknora.plugin.v1.ShutdownRequest\x1a\x16.google.protobuf.Empty2\xab\x02\n" +
	"\x10DataSourcePlugin\x12b\n" +
	"\rListResources\x12'.weknora.plugin.v1.ListResourcesRequest\x1a(.weknora.plugin.v1.ListResourcesResponse\x12k\n" +
	"\x10ResolveAncestors\x12*.weknora.plugin.v1.ResolveAncestorsRequest\x1a+.weknora.plugin.v1.ResolveAncestorsResponse\x12F\n" +
	"\x04Sync\x12\x1e.weknora.plugin.v1.SyncRequest\x1a\x1c.weknora.plugin.v1.SyncEvent0\x01B9Z7github.com/Tencent/WeKnora/pkg/plugin/proto/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(ExtensionType)(0),               // 0: weknora.plugin.v1.ExtensionType
	(HealthStatus)(0),                // 1: weknora.plugin.v1.HealthStatus
	(*PluginError)(nil),              // 2: weknora.plugin.v1.PluginError
	(*HandshakeRequest)(nil),         // 3: weknora.plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil),        // 4: weknora.plugin.v1.HandshakeResponse
	(*ValidateConfigRequest)(nil),    // 5: weknora.plugin.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),   // 6: weknora.plugin.v1.ValidateConfigResponse
	(*HealthRequest)(nil),            // 7: weknora.plugin.v1.HealthRequest
	(*HealthResponse)(nil),           // 8: weknora.plugin.v1.HealthResponse
	(*ShutdownRequest)(nil),          // 9: weknora.plugin.v1.ShutdownRequest
	(*ListResourcesRequest)(nil),     // 10: weknora.plugin.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 11: weknora.plugin.v1.ListResourcesResponse
	(*Resource)(nil),                 // 12: weknora.plugin.v1.Resource
	(*ResolveAncestorsRequest)(nil),  // 13: weknora.plugin.v1.ResolveAncestorsRequest
	(*ResolveAncestorsResponse)(nil), // 14: weknora.plugin.v1.ResolveAncestorsResponse
	(*SyncRequest)(nil),              // 15: weknora.plugin.v1.SyncRequest
	(*SyncEvent)(nil),                // 16: weknora.plugin.v1.SyncEvent
	(*DocumentUpsert)(nil),           // 17: weknora.plugin.v1.DocumentUpsert
	(*DocumentDelete)(nil),           // 18: weknora.plugin.v1.DocumentDelete
	(*ItemError)(nil),                // 19: weknora.plugin.v1.ItemError
	(*Checkpoint)(nil),               // 20: weknora.plugin.v1.Checkpoint
	nil,                              // 21: weknora.plugin.v1.DocumentUpsert.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 23: google.protobuf.Empty
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	0,  // 0: weknora.plugin.v1.HandshakeRequest.extension_type:type_name -> weknora.plugin.v1.ExtensionType
	0,  // 1: weknora.plugin.v1.HandshakeResponse.extension_type:type_name -> weknora.plugin.v1.ExtensionType
	2,  // 2: weknora.plugin.v1.HandshakeResponse.error:type_name -> weknora.plugin.v1.PluginError
	2,  // 3: weknora.plugin.v1.ValidateConfigResponse.error:type_name -> weknora.plugin.v1.PluginError
	1,  // 4: weknora.plugin.v1.HealthResponse.status:type_name -> weknora.plugin.v1.HealthStatus
	2,  // 5: weknora.plugin.v1.HealthResponse.error:type_name -> weknora.plugin.v1.PluginError
	22, // 6: weknora.plugin.v1.HealthResponse.checked_at:type_name -> google.protobuf.Timestamp
	12, // 7: weknora.plugin.v1.ListResourcesResponse.resources:type_name -> weknora.plugin.v1.Resource
	2,  // 8: weknora.plugin.v1.ListResourcesResponse.error:type_name -> weknora.plugin.v1.PluginError
	22, // 9: weknora.plugin.v1.Resource.modified_at:type_name -> google.protobuf.Timestamp
	2,  // 10: weknora.plugin.v1.ResolveAncestorsResponse.error:type_name -> weknora.plugin.v1.PluginError
	17, // 11: weknora.plugin.v1.SyncEvent.upsert:type_name -> weknora.plugin.v1.DocumentUpsert
	18, // 12: weknora.plugin.v1.SyncEvent.delete:type_name -> weknora.plugin.v1.DocumentDelete
	19, // 13: weknora.plugin.v1.SyncEvent.item_error:type_name -> weknora.plugin.v1.ItemError
	20, // 14: weknora.plugin.v1.SyncEvent.checkpoint:type_name -> weknora.plugin.v1.Checkpoint
	22, // 15: weknora.plugin.v1.DocumentUpsert.updated_at:type_name -> google.protobuf.Timestamp
	21, // 16: weknora.plugin.v1.DocumentUpsert.metadata:type_name -> weknora.plugin.v1.DocumentUpsert.MetadataEntry
	3,  // 17: weknora.plugin.v1.PluginControl.Handshake:input_type -> weknora.plugin.v1.HandshakeRequest
	5,  // 18: weknora.plugin.v1.PluginControl.ValidateConfig:input_type -> weknora.plugin.v1.ValidateConfigRequest
	7,  // 19: weknora.plugin.v1.PluginControl.Health:input_type -> weknora.plugin.v1.HealthRequest
	9,  // 20: weknora.plugin.v1.PluginControl.Shutdown:input_type -> weknora.plugin.v1.ShutdownRequest
	10, // 21: weknora.plugin.v1.DataSourcePlugin.ListResources:input_type -> weknora.plugin.v1.ListResourcesRequest
	13, // 22: weknora.plugin.v1.DataSourcePlugin.ResolveAncestors:input_type -> weknora.plugin.v1.ResolveAncestorsRequest
	15, // 23: weknora.plugin.v1.DataSourcePlugin.Sync:input_type -> weknora.plugin.v1.SyncRequest
	4,  // 24: weknora.plugin.v1.PluginControl.Handshake:output_type -> weknora.plugin.v1.HandshakeResponse
	6,  // 25: weknora.plugin.v1.PluginControl.ValidateConfig:output_type -> weknora.plugin.v1.ValidateConfigResponse
	8,  // 26: weknora.plugin.v1.PluginControl.Health:output_type -> weknora.plugin.v1.HealthResponse
	23, // 27: weknora.plugin.v1.PluginControl.Shutdown:output_type -> google.protobuf.Empty
	11, // 28: weknora.plugin.v1.DataSourcePlugin.ListResources:output_type -> weknora.plugin.v1.ListResourcesResponse
	14, // 29: weknora.plugin.v1.DataSourcePlugin.ResolveAncestors:output_type -> weknora.plugin.v1.ResolveAncestorsResponse
	16, // 30: weknora.plugin.v1.DataSourcePlugin.Sync:output_type -> weknora.plugin.v1.SyncEvent
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	file_plugin_v1_plugin_proto_msgTypes[14].OneofWrappers = []any{
		(*SyncEvent_Upsert)(nil),
		(*SyncEvent_Delete)(nil),
		(*SyncEvent_ItemError)(nil),
		(*SyncEvent_Checkpoint)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
