// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.0
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginControl_Handshake_FullMethodName      = "/weknora.plugin.v1.PluginControl/Handshake"
	PluginControl_ValidateConfig_FullMethodName = "/weknora.plugin.v1.PluginControl/ValidateConfig"
	PluginControl_Health_FullMethodName         = "/weknora.plugin.v1.PluginControl/Health"
	PluginControl_Shutdown_FullMethodName       = "/weknora.plugin.v1.PluginControl/Shutdown"
)

// PluginControlClient is the client API for PluginControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginControlClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pluginControlClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginControlClient(cc grpc.ClientConnInterface) PluginControlClient {
	return &pluginControlClient{cc}
}

func (c *pluginControlClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, PluginControl_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, PluginControl_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PluginControl_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginControlServer is the server API for PluginControl service.
// All implementations must embed UnimplementedPluginControlServer
// for forward compatibility.
type PluginControlServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPluginControlServer()
}

// UnimplementedPluginControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginControlServer struct{}

func (UnimplementedPluginControlServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginControlServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedPluginControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginControlServer) Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginControlServer) mustEmbedUnimplementedPluginControlServer() {}
func (UnimplementedPluginControlServer) testEmbeddedByValue()                       {}

// UnsafePluginControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginControlServer will
// result in compilation errors.
type UnsafePluginControlServer interface {
	mustEmbedUnimplementedPluginControlServer()
}

func RegisterPluginControlServer(s grpc.ServiceRegistrar, srv PluginControlServer) {
	// If the following call panics, it indicates UnimplementedPluginControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginControl_ServiceDesc, srv)
}

func _PluginControl_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginControl_ServiceDesc is the grpc.ServiceDesc for PluginControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.PluginControl",
	HandlerType: (*PluginControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginControl_Handshake_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _PluginControl_ValidateConfig_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginControl_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginControl_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/plugin.proto",
}

const (
	DataSourcePlugin_ListResources_FullMethodName    = "/weknora.plugin.v1.DataSourcePlugin/ListResources"
	DataSourcePlugin_ResolveAncestors_FullMethodName = "/weknora.plugin.v1.DataSourcePlugin/ResolveAncestors"
	DataSourcePlugin_Sync_FullMethodName             = "/weknora.plugin.v1.DataSourcePlugin/Sync"
)

// DataSourcePluginClient is the client API for DataSourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataSourcePluginClient interface {
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	ResolveAncestors(ctx context.Context, in *ResolveAncestorsRequest, opts ...grpc.CallOption) (*ResolveAncestorsResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEvent], error)
}

type dataSourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourcePluginClient(cc grpc.ClientConnInterface) DataSourcePluginClient {
	return &dataSourcePluginClient{cc}
}

func (c *dataSourcePluginClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) ResolveAncestors(ctx context.Context, in *ResolveAncestorsRequest, opts ...grpc.CallOption) (*ResolveAncestorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAncestorsResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ResolveAncestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSourcePlugin_ServiceDesc.Streams[0], DataSourcePlugin_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncClient = grpc.ServerStreamingClient[SyncEvent]

// DataSourcePluginServer is the server API for DataSourcePlugin service.
// All implementations must embed UnimplementedDataSourcePluginServer
// for forward compatibility.
type DataSourcePluginServer interface {
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	ResolveAncestors(context.Context, *ResolveAncestorsRequest) (*ResolveAncestorsResponse, error)
	Sync(*SyncRequest, grpc.ServerStreamingServer[SyncEvent]) error
	mustEmbedUnimplementedDataSourcePluginServer()
}

// UnimplementedDataSourcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourcePluginServer struct{}

func (UnimplementedDataSourcePluginServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedDataSourcePluginServer) ResolveAncestors(context.Context, *ResolveAncestorsRequest) (*ResolveAncestorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAncestors not implemented")
}
func (UnimplementedDataSourcePluginServer) Sync(*SyncRequest, grpc.ServerStreamingServer[SyncEvent]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDataSourcePluginServer) mustEmbedUnimplementedDataSourcePluginServer() {}
func (UnimplementedDataSourcePluginServer) testEmbeddedByValue()                          {}

// UnsafeDataSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourcePluginServer will
// result in compilation errors.
type UnsafeDataSourcePluginServer interface {
	mustEmbedUnimplementedDataSourcePluginServer()
}

func RegisterDataSourcePluginServer(s grpc.ServiceRegistrar, srv DataSourcePluginServer) {
	// If the following call panics, it indicates UnimplementedDataSourcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourcePlugin_ServiceDesc, srv)
}

func _DataSourcePlugin_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_ResolveAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ResolveAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ResolveAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ResolveAncestors(ctx, req.(*ResolveAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSourcePluginServer).Sync(m, &grpc.GenericServerStream[SyncRequest, SyncEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncServer = grpc.ServerStreamingServer[SyncEvent]

// DataSourcePlugin_ServiceDesc is the grpc.ServiceDesc for DataSourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DataSourcePlugin",
	HandlerType: (*DataSourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResources",
			Handler:    _DataSourcePlugin_ListResources_Handler,
		},
		{
			MethodName: "ResolveAncestors",
			Handler:    _DataSourcePlugin_ResolveAncestors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _DataSourcePlugin_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/v1/plugin.proto",
}
